### ISSUE TITLE
Multi-line SubmitLine breaks parsing

### ISSUE THREAD

**Issue by cthomas-rivos** [troycomi/reportseff#63]
**Describe the bug**
Multi-line SubmitLines break the parser

**To Reproduce**
1. submit a job whose SubmitLine is multiple lines, for example
```
srun bash -c "echo hello &&      (press enter)
echo goodbye"
```
2. ask reportseff for a report including the SubmitLine: `reportseff  1234 --format="+SumbitLine"`
3. Receive python stack trace.
```
  File "/home/user/.local/lib/python3.10/site-packages/reportseff/job_collection.py", line 204, in process_entry
    job_id = entry["JobID"].split(".")[0]
KeyError: 'JobID'`
```

**Expected behavior**
Not crash

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
 - Version:
 ```
commit b826d801abc204a13c606f904bae6741885b8e8d (HEAD -> main, tag: v2.8.0, origin/main, origin/HEAD)
Author: Joel Lafond-Lapalme <joel.lafond.lapalme@gmail.com>
Date:   Thu Oct 3 10:55:00 2024 -0400
```

**Debug Output**
```
^|^1^|^00:00:02^|^59374177^|^59374177^|^^|^1^|^^|^2097M^|^COMPLETED^|^srun  --interactive --pty bash -c echo hello &&
echo goodbye^|^20:00:00^|^00:00.042
^|^1^|^00:00:02^|^59374177.interactive^|^59374177.interactive^|^0^|^1^|^1^|^^|^COMPLETED^|^srun  --interactive --pty bash -c echo hello &&
echo goodbye^|^^|^00:00.039
^|^1^|^00:00:02^|^59374177.extern^|^59374177.extern^|^0^|^1^|^1^|^^|^COMPLETED^|^^|^^|^00:00.002

Error processing entry: {'AdminComment': 'echo goodbye', 'AllocCPUS': '20:00:00', 'Elapsed': '00:00.042'}
```

**Additional context**
`sacct` is returning the data split on multiple lines. I _think_ it's still properly setting up the delimiters, but I don't have the resources at the moment to come up with a good solution (maybe checking whether a line has too few columns, then trying to merge the next line if so?).

**Comment by troycomi** [comment]
A very devious use case...  I'll need to think about how best to deal with this, may be a couple days before I can release a patch.  It does seem like the delimiters are ok.  I need to look into sacct information to see if I can set the line-delimiter and see how I'm consuming sacct output.

Thank you for the detailed bug report.

**Comment by troycomi** [comment]
Mostly a note for me, it looks like `--parsable` in sacct adds a delimiter at the end of the line, but I may be using `--parsable2`, which does not add the delimiter.  Should be as easy as changing the line splitting from `\n` to `^|^\n` and updating tests.

**Comment by troycomi** [comment]
This should be fixed in v2.8.1.  Also when you print debug outputs you should get a `\n` for the internal tokens.  Reach out if you have problems!

**Comment by cthomas-rivos** [comment]
Thanks this works great. Do you think it would make sense to use `\n` for the non-debug output as well? I'm weakly in favor of replacing newlines there so each job is one line, because I often sort the output by particular columns, e.g. to first look for memory-inefficient jobs, then cpu-inefficient jobs, etc.

**Comment by troycomi** [comment]
Probably, honestly I wasn't sure what your use case was!

I should use a regex to make that more efficient since it will affect all calls.  I may have time to patch that next week.

**Comment by troycomi** [comment]
Should be good in 2.8.2
